### PR TITLE
Fix script demonstration

### PR DESCRIPTION
**Pull request by EzzEddin**

### CODE REVIEW

**Comment by pythoninthegrass** [comment]
Hi @EzzEddin! Thanks for the PR! Please update your fork's `poetry.lock` and `requirements.txt` files and I'll be happy to merge your changes.

Can also upload a real note that I'm using — there's thousands of them haha

**Comment by pythoninthegrass** [comment]
Actually, easy to just copy/paste my versions. In case you're interested, using [poetry](https://python-poetry.org/docs/basic-usage/#project-setup) to handle dependencies:
```bash
poetry install
poetry add <dependency>
poetry export -f requirements.txt --output requirements.txt --without-hashes
```

**Comment by EzzEddin** [comment]
> Actually, easy to just copy/paste my versions. In case you're interested, using [poetry](https://python-poetry.org/docs/basic-usage/#project-setup) to handle dependencies:
> 
> ```shell
> poetry install
> poetry add <dependency>
> poetry export -f requirements.txt --output requirements.txt --without-hashes
> ```

That's really good! Can you add it please to the README? as this is my first time hearing about Poetry and probably some people who land on your repo might ignore Poetry too.

**Comment by EzzEddin** [comment]
> Hi @EzzEddin! Thanks for the PR! Please update your fork's `poetry.lock` and `requirements.txt` files and I'll be happy to merge your changes.
> 
> Can also upload a real note that I'm using — there's thousands of them haha

Probably you fixed that merge conflict, right? :)

**Comment by pythoninthegrass** [comment]
> > Actually, easy to just copy/paste my versions. In case you're interested, using [poetry](https://python-poetry.org/docs/basic-usage/#project-setup) to handle dependencies:
> > ```shell
> > poetry install
> > poetry add <dependency>
> > poetry export -f requirements.txt --output requirements.txt --without-hashes
> > ```
> 
> That's really good! Can you add it please to the README? as this is my first time hearing about Poetry and probably some people who land on your repo might ignore Poetry too.

Done! (https://github.com/pythoninthegrass/convert_html_md/commit/cd95afcf83878c50b685d9bc48779e44cbe82cbe)

> Probably you fixed that merge conflict, right? :)

Yessir!

**Pull request merged**
